# Generated by Django 5.0.3 on 2024-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('locker_number', models.IntegerField(max_length=6)),
                ('locker_combination', models.CharField(max_length=15)),
                ('good_student', models.BooleanField()),
            ],
        ),
    ]
